# 重试异步函数

实现 Promise.retry，重试异步函数，异步函数执行成功后 resolve 结果，失败后重试，尝试超过一定次数才真正的 reject。

```javascript
//用 setTimeout 模拟异步函数
function fn() {
  const n = Math.random();
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (n > 0.7) {
        resolve(n);
      } else {
        reject(n);
      }
    }, 1000);
  });
}
//Promise.retry 方法
Promise.retry = (fn, times) => {
  new Promise(async (resolve, reject) => {
    while (times--) {
      try {
        const res = await fn();
        console.log("执行成功，得到的结果是:", res);
      } catch (error) {
        console.log("执行失败一次，得到的结果是", error);
        if (!times) {
          reject(error);
        }
      }
    }
  }).catch(() => {
    console.log("全部次数执行完成，仍然失败");
  });
};

Promise.retry(fn, 3);

```

